FizzBuzz.Web/Models/FizzBuzzModel.cs
using System.ComponentModel.DataAnnotations;
using PagedList;

namespace FizzBuzz.Web.Models
{
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "Please enter a valid value")]
        [Range(1,1000, ErrorMessage = "Please enter a value within the range 1 to 1000")]
        public int UserInput { get; set;  }
        public IPagedList<string> ResultList { get; set; }
    }
}

FizzBuzz.Web/Controllers/FizzBuzzController.cs
using System.Web.Mvc;
using FizzBuzz.Web.Models;

using FizzBuzz.Business.Interfaces;
using PagedList;

namespace FizzBuzz.Web.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService fizzBuzzService;
        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }
        
        // GET: FizzBuzz
        [HttpGet]
        public ActionResult Index()
        {
            return View(new FizzBuzzModel());
        }

        [HttpGet]
        public ActionResult FizzBuzzList(FizzBuzzModel fizzBuzzModel, int? page)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", fizzBuzzModel);
            }
            var finaloutput = this.fizzBuzzService.GetFizzBuzzList(fizzBuzzModel.UserInput);
            fizzBuzzModel.ResultList = finaloutput.ToPagedList(page ?? 1, 20);
            return View("Index", fizzBuzzModel);
        }
    }
}

FizzBuzz.Web/Views/FizzBuzz/FizzBuzzList.cshtml
@model FizzBuzz.Web.Models.FizzBuzzModel

@{
    ViewBag.Title = "Fizz-Buzz List";
}

@using PagedList
@using PagedList.Mvc

<h2>Output</h2>

<link href="~/Styles/FizzBuzz.css" rel="stylesheet" type="text/css" />
@Html.AntiForgeryToken()

@foreach (var element in Model.ResultList)
{
    var wordlist = element.Split(' ');
    if (wordlist.Count() > 1)
    {
        <p>
            @foreach (var word in wordlist)
            {
                <span class="@word">@word</span>
            }
        </p>

    }
    else
    {
        <P class="@element">@element</P>
    }
}

@Html.PagedListPager((IPagedList)Model.ResultList, page => Url.Action("FizzBuzzList", "FizzBuzz", new { page = page, UserInput = Model.UserInput }), PagedListRenderOptions.MinimalWithPageCountText)

FizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Web.Models.FizzBuzzModel

@{
    ViewBag.Title = "Fizz-Buzz Web Application";
}

<h2>Fizz-Buzz web application</h2>
@using (Html.BeginForm("FizzBuzzList", "FizzBuzz", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    <label for="userinput">Please enter a value: -</label>

    <div>
        @Html.ValidationMessageFor(m => m.UserInput, "")
        <div>
            @Html.TextBoxFor(m => m.UserInput, new { Value = "" })
        </div>
    </div>
    <div>
        <button type="submit" name="submit" class="btn btn-info" id="submit" value="submit">submit</button>
    </div>


    if (Model.ResultList != null)
    {
        @Html.Partial("FizzBuzzList", Model)
    }
}

FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>